import { sqliteTable, text, integer, real } from 'drizzle-orm/sqlite-core';

export const boxers = sqliteTable('boxers', {
  id: text('id').primaryKey().notNull(),
  boxrecId: text('boxrecId').notNull(),
  boxrecUrl: text('boxrecUrl').notNull(),
  boxrecWikiUrl: text('boxrecWikiUrl'),
  slug: text('slug').notNull(),
  name: text('name').notNull(),
  birthName: text('birthName'),
  nicknames: text('nicknames'),
  avatarImage: text('avatarImage'),
  residence: text('residence'),
  birthPlace: text('birthPlace'),
  dateOfBirth: text('dateOfBirth'),
  gender: text('gender'),
  nationality: text('nationality'),
  height: text('height'),
  reach: text('reach'),
  stance: text('stance'),
  bio: text('bio'),
  promoters: text('promoters'),
  trainers: text('trainers'),
  managers: text('managers'),
  gym: text('gym'),
  
  // Professional stats
  proDebutDate: text('proDebutDate'),
  proDivision: text('proDivision'),
  proWins: integer('proWins').default(0).notNull(),
  proWinsByKnockout: integer('proWinsByKnockout').default(0).notNull(),
  proLosses: integer('proLosses').default(0).notNull(),
  proLossesByKnockout: integer('proLossesByKnockout').default(0).notNull(),
  proDraws: integer('proDraws').default(0).notNull(),
  proStatus: text('proStatus'),
  proTotalBouts: integer('proTotalBouts'),
  proTotalRounds: integer('proTotalRounds'),
  
  // Amateur stats
  amateurDebutDate: text('amateurDebutDate'),
  amateurDivision: text('amateurDivision'),
  amateurWins: integer('amateurWins'),
  amateurWinsByKnockout: integer('amateurWinsByKnockout'),
  amateurLosses: integer('amateurLosses'),
  amateurLossesByKnockout: integer('amateurLossesByKnockout'),
  amateurDraws: integer('amateurDraws'),
  amateurStatus: text('amateurStatus'),
  amateurTotalBouts: integer('amateurTotalBouts'),
  amateurTotalRounds: integer('amateurTotalRounds'),
  
  createdAt: text('createdAt').default('CURRENT_TIMESTAMP').notNull(),
  updatedAt: text('updatedAt').default('CURRENT_TIMESTAMP').notNull(),
});