name = "boxing-pipeline"
compatibility_date = "2023-05-18"

# Load account ID from environment
account_id = "cec5f04e1d18bcc65f2be0aefb04f059"

[[d1_databases]]
binding = "DB"
database_name = "boxingundefeated-com-preview"
database_id = "9dde6ccf-fc52-41a3-9268-1a92dabaafb7"