name = "boxing-pipeline"
compatibility_date = "2023-05-18"

# Load account ID from environment
account_id = "cec5f04e1d18bcc65f2be0aefb04f059"

[[d1_databases]]
binding = "DB"
database_name = "boxingundefeated-com"
database_id = "6b463a07-05a9-4da1-9637-f8331d40b36c"